### ISSUE TITLE
Twitter API Update 

### ISSUE THREAD

**Issue by spencer0523** [jclishman/SpaceXMirrorBot#1]
https://github.com/jclishman/SpaceXMirrorBot/blob/e757dc59031159475dc7d2a14a36ed5233540f6c/bot.py#L24

Hey, I recently updated this on my local machine to use twitter api v2 and all you need is a bearer token instead; I was wondering if you wanted me a pull request to merge changes?

**Comment by jclishman** [comment]
Yeah. sounds good
